name: Branch Tests

on:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.6'
          cache: true
      
      - name: Download dependencies
        run: go mod download
      
      - name: Build project
        run: make build
      
      - name: Run tests
        run: make test
      
      - name: Clean up
        run: make clean